TEAM_ALIASES: dict[str, str] = {
    "t1": "T1",
    "skt": "T1",
    "sk telecom t1": "T1",
    "skt t1": "T1",
    "gen.g": "Gen.G",
    "gen g": "Gen.G",
    "gen.g esports": "Gen.G",
    "geng": "Gen.G",
    "samsung galaxy": "Gen.G",
    "hanwha life esports": "Hanwha Life Esports",
    "hle": "Hanwha Life Esports",
    "dplus kia": "Dplus KIA",
    "dk": "Dplus KIA",
    "dwg kia": "Dplus KIA",
    "damwon gaming": "Dplus KIA",
    "damwon kia": "Dplus KIA",
    "kt rolster": "KT Rolster",
    "kt": "KT Rolster",
    "drx": "DRX",
    "kwangdong freecs": "Kwangdong Freecs",
    "kdf": "Kwangdong Freecs",
    "dn soopers": "DN Soopers",
    "nongshim redforce": "DN Soopers",
    "ns redforce": "DN Soopers",
    "brion": "OKSavingsBank BRION",
    "oksavingsbank brion": "OKSavingsBank BRION",
    "fredit brion": "OKSavingsBank BRION",
    "bro": "OKSavingsBank BRION",

    "bilibili gaming": "Bilibili Gaming",
    "blg": "Bilibili Gaming",
    "jd gaming": "JD Gaming",
    "jdg": "JD Gaming",
    "top esports": "Top Esports",
    "tes": "Top Esports",
    "weibo gaming": "Weibo Gaming",
    "wbg": "Weibo Gaming",
    "lng esports": "LNG Esports",
    "lng": "LNG Esports",
    "royal never give up": "Royal Never Give Up",
    "rng": "Royal Never Give Up",
    "edg": "EDward Gaming",
    "edward gaming": "EDward Gaming",
    "funplus phoenix": "FunPlus Phoenix",
    "fpx": "FunPlus Phoenix",

    "g2 esports": "G2 Esports",
    "g2": "G2 Esports",
    "fnatic": "Fnatic",
    "fnc": "Fnatic",
    "mad lions": "MAD Lions KOI",
    "mad lions koi": "MAD Lions KOI",
    "mad": "MAD Lions KOI",
    "team vitality": "Team Vitality",
    "vit": "Team Vitality",
    "team heretics": "Team Heretics",
    "th": "Team Heretics",
    "karmine corp": "Karmine Corp",
    "kc": "Karmine Corp",
    "giantx": "GiantX",
    "rogue": "Rogue",
    "sk gaming": "SK Gaming",
    "sk": "SK Gaming",

    "team liquid": "Team Liquid",
    "team liquid honda": "Team Liquid",
    "tl": "Team Liquid",
    "cloud9": "Cloud9",
    "c9": "Cloud9",
    "flyquest": "FlyQuest",
    "fly": "FlyQuest",
    "100 thieves": "100 Thieves",
    "100t": "100 Thieves",
    "dignitas": "Dignitas",
    "dig": "Dignitas",
    "evil geniuses": "Evil Geniuses",
    "eg": "Evil Geniuses",
    "nrg esports": "NRG Esports",
    "nrg": "NRG Esports",
    "immortals": "Immortals",
    "imt": "Immortals",
    "golden guardians": "Golden Guardians",
    "gg": "Golden Guardians",
    "tsm": "TSM",
    "counter logic gaming": "Counter Logic Gaming",
    "clg": "Counter Logic Gaming",
    "shopify rebellion": "Shopify Rebellion",
    "sr": "Shopify Rebellion",
    "disguised": "Disguised",
    "dsg": "Disguised",
    "lions esports": "Lions Esports",

    "bnk fearx": "BNK FearX",
    "bfx": "BNK FearX",
    "lyon": "LYON",
    "lyon esports": "LYON",
    "team secret whales": "Team Secret Whales",
    "team secret": "Team Secret Whales",
    "ts whales": "Team Secret Whales",
    "loud": "LOUD",
    "pain gaming": "paiN Gaming",
    "pain": "paiN Gaming",
    "furia": "FURIA",
    "furia esports": "FURIA",
    "red canids": "RED Canids",
    "kabum! esports": "KaBuM! Esports",
    "kabum": "KaBuM! Esports",
    "fluxo": "Fluxo",
    "isurus": "Isurus",
    "leviatan": "Leviatán",
    "leviatán": "Leviatán",
    "estral esports": "Estral Esports",
    "estral": "Estral Esports",
    "all knights": "All Knights",

    "psg talon": "PSG Talon",
    "psg": "PSG Talon",
    "cfо": "CFO",
    "beyond gaming": "Beyond Gaming",
    "frank esports": "Frank Esports",

    "gam esports": "GAM Esports",
    "gam": "GAM Esports",
    "team flash": "Team Flash",
    "fl": "Team Flash",
    "mgn vikings esports": "MGN Vikings Esports",

    "detonation focusme": "DetonatioN FocusMe",
    "dfm": "DetonatioN FocusMe",
}

PLAYER_ALIASES: dict[str, str] = {
    "faker": "Faker",
    "이상혁": "Faker",
    "skt faker": "Faker",
    "hide on bush": "Faker",
    "chovy": "Chovy",
    "showmaker": "ShowMaker",
    "canyon": "Canyon",
    "keria": "Keria",
    "gumayusi": "Gumayusi",
    "zeus": "Zeus",
    "oner": "Oner",
    "gala": "GALA",
    "knight": "Knight",
    "elk": "Elk",
    "bin": "Bin",
    "tian": "Tian",
    "caps": "Caps",
    "yike": "Yike",
    "mikyx": "Mikyx",
    "hans sama": "Hans Sama",
    "broken blade": "Broken Blade",
    "brokenblade": "Broken Blade",
}

CHAMPION_ALIASES: dict[str, str] = {
    "monkeyking": "Wukong",
    "monkey king": "Wukong",
    "wukong": "Wukong",
    "nunu & willump": "Nunu",
    "nunu and willump": "Nunu",
    "nunu": "Nunu",
    "renata glasc": "Renata Glasc",
    "renata": "Renata Glasc",
    "k'sante": "K'Sante",
    "ksante": "K'Sante",
    "bel'veth": "Bel'Veth",
    "belveth": "Bel'Veth",
    "kai'sa": "Kai'Sa",
    "kaisa": "Kai'Sa",
    "kha'zix": "Kha'Zix",
    "khazix": "Kha'Zix",
    "cho'gath": "Cho'Gath",
    "chogath": "Cho'Gath",
    "kog'maw": "Kog'Maw",
    "kogmaw": "Kog'Maw",
    "rek'sai": "Rek'Sai",
    "reksai": "Rek'Sai",
    "vel'koz": "Vel'Koz",
    "velkoz": "Vel'Koz",
    "lee sin": "Lee Sin",
    "twisted fate": "Twisted Fate",
    "miss fortune": "Miss Fortune",
    "aurelion sol": "Aurelion Sol",
    "tahm kench": "Tahm Kench",
    "xin zhao": "Xin Zhao",
    "jarvan iv": "Jarvan IV",
    "dr. mundo": "Dr. Mundo",
    "dr mundo": "Dr. Mundo",
    "master yi": "Master Yi",
}

LEAGUE_ALIASES: dict[str, str] = {
    "lta north": "LTAN",
    "lta north 2025": "LTAN",
    "lta north 2026": "LTAN",
    "ltan": "LTAN",
    "lta south": "LTAS",
    "lta south 2025": "LTAS",
    "lta south 2026": "LTAS",
    "ltas": "LTAS",
    "lcs": "LCS",
    "na lcs": "LCS",
    "lec": "LEC",
    "eu lcs": "LEC",
    "lck": "LCK",
    "lpl": "LPL",
    "cblol": "CBLOL",
    "lla": "LLA",
    "liga latinoamérica": "LLA",
    "liga latinoamerica": "LLA",
    "pcs": "PCS",
    "vcs": "VCS",
    "ljl": "LJL",
    "lco": "LCO",
    "lcp": "LCP",
    "worlds": "Worlds",
    "world championship": "Worlds",
    "msi": "MSI",
    "mid-season invitational": "MSI",
    "mid season invitational": "MSI",
    "esports world cup": "EWC",
    "ewc": "EWC",
    "first stand": "FST",
    "fst": "FST",
    "dcup": "DCup",
    "demacia cup": "DCup",
    "lckc": "LCKC",
    "lckcl": "LCKCL",
    "lfl": "LFL",
    "nacl": "NACL",
    "emea masters": "EMEA Masters",
}
